Resources:
  myBucket5AF9C99B:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: workshop-cdk-typescript-jm
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: WorkshopJmStack/myBucket/Resource
  myLambdaServiceRole5879F9B1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: WorkshopJmStack/myLambda/ServiceRole/Resource
  myLambdaServiceRoleDefaultPolicy3782F84B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - myBucket5AF9C99B
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - myBucket5AF9C99B
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: myLambdaServiceRoleDefaultPolicy3782F84B
      Roles:
        - Ref: myLambdaServiceRole5879F9B1
    Metadata:
      aws:cdk:path: WorkshopJmStack/myLambda/ServiceRole/DefaultPolicy/Resource
  myLambda696B54F1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-277756974081-ap-southeast-2
        S3Key: 6b87b58e65880f64d6b9e23ef9affbf7564cc61cefe49682aff09240e9e62fed.zip
      Role:
        Fn::GetAtt:
          - myLambdaServiceRole5879F9B1
          - Arn
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
    DependsOn:
      - myLambdaServiceRoleDefaultPolicy3782F84B
      - myLambdaServiceRole5879F9B1
    Metadata:
      aws:cdk:path: WorkshopJmStack/myLambda/Resource
      aws:asset:path: asset.6b87b58e65880f64d6b9e23ef9affbf7564cc61cefe49682aff09240e9e62fed
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWOTQ6CMBCFz+J+GEUSw1ZMXBs8ACllJIXSJkyrMU3vLgVcfe9nMnlnLHM8HcSHM9mNmVYthqcTcoQlagIXGCovR3Jwe5ldbagEUwQtprYTGO7eSKesSWd/HUGJCUNtNaV45cNqJb/JbioCF41gJsd4TYhQE1s/S4LVL2N6Zfr1wV5EMLYjHPj4zkvML8v+gZXKZm+cmgjrjT/RjN2Y2wAAAA==
    Metadata:
      aws:cdk:path: WorkshopJmStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

